# Generated by Django 4.0.4 on 2022-05-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='', upload_to='users/photos', verbose_name='Photo'),
        ),
    ]
