# Generated by Django 4.0.4 on 2022-05-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(default='The ones that love us never really leave us. And you can always find them in here.. — Sirius Black', verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='/media/users/photos/default.jpg', upload_to='users/photos', verbose_name='Photo'),
        ),
    ]
